# Analysis options for FillExchange
# Configured per Story 1.1 AC-5

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    prefer_const_declarations: true
    prefer_final_locals: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    require_trailing_commas: true

analyzer:
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
