import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import 'package:go_router/go_router.dart';
import 'package:fill_exchange/core/services/storage_service.dart';
import 'package:fill_exchange/features/auth/repositories/auth_repository.dart';
import 'package:geolocator/geolocator.dart';
import '../../../core/models/geo_point.dart';
import '../models/listing_model.dart';
import '../repositories/listing_repository.dart';
import '../../maps/screens/location_picker_screen.dart';
import '../../maps/widgets/static_map_preview.dart';

class CreateListingScreen extends ConsumerStatefulWidget {
  const CreateListingScreen({super.key});

  @override
  ConsumerState<CreateListingScreen> createState() => _CreateListingScreenState();
}

enum _Step { basic, details, location, photos }

class _CreateListingScreenState extends ConsumerState<CreateListingScreen> {
  _Step _currentStep = _Step.basic;
  bool _isLoading = false;

  // Form Data
  ListingType _type = ListingType.offering;
  FillMaterial _material = FillMaterial.cleanFill;
  final _qtyController = TextEditingController();
  VolumeUnit _unit = VolumeUnit.cubicYards;
  final _priceController = TextEditingController();
  bool _isFree = true;
  String? _currency = 'USD';
  final _addressController = TextEditingController();
  final _descriptionController = TextEditingController();
  final List<XFile> _selectedPhotos = [];
  GeoPoint? _currentLocation;

  final _formKey = GlobalKey<FormState>();

  @override
  void dispose() {
    _qtyController.dispose();
    _priceController.dispose();
    _addressController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    final picked = await picker.pickImage(source: ImageSource.gallery);
    if (picked != null) {
      setState(() => _selectedPhotos.add(picked));
    }
  }

  Future<void> _getCurrentLocation() async {
    bool serviceEnabled;
    LocationPermission permission;

    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Location services are disabled.')));
      return;
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Location permissions are denied')));
        return;
      }
    }
    
    if (permission == LocationPermission.deniedForever) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Location permissions are permanently denied.')));
      return;
    } 

    setState(() => _isLoading = true);
    try {
      final position = await Geolocator.getCurrentPosition();
      setState(() {
        _currentLocation = GeoPoint(position.latitude, position.longitude);
        // If address is empty, fill with coords as placeholder
        if (_addressController.text.isEmpty) {
           _addressController.text = "Lat: ${position.latitude.toStringAsFixed(4)}, Lng: ${position.longitude.toStringAsFixed(4)}";
        }
      });
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Location Acquired!')));
    } catch (e) {
       if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error getting location: $e')));
    } finally {
       if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);
    
    try {
      final user = ref.read(authRepositoryProvider).currentUser;
      if (user == null) throw Exception('No user logged in');

      // Upload Photos
      final storage = ref.read(storageServiceProvider);
      List<String> photoUrls = [];
      for (var file in _selectedPhotos) {
        final path = 'listings/${user.id}/${DateTime.now().millisecondsSinceEpoch}_${file.name}';
        final url = await storage.uploadFile(localPath: file.path, remotePath: path);
        if (url != null) photoUrls.add(url);
      }

      final listing = Listing(
        id: '', // Auto-generated by repo
        hostUid: user.id,
        type: _type,
        material: _material,
        quantity: double.tryParse(_qtyController.text) ?? 0.0,
        unit: _unit,
        price: _isFree ? 0.0 : (double.tryParse(_priceController.text) ?? 0.0),
        currency: _currency!,
        description: _descriptionController.text.trim(),
        photos: photoUrls,
        address: _addressController.text.trim(),
        location: _currentLocation,
        createdAt: DateTime.now(),
      );

      await ref.read(listingRepositoryProvider).createListing(listing);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Listing Created!')));
        context.pop(); // Return to previous screen (Home)
      }
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  // --- UI Step Builders ---

  Widget _buildBasicInfo() {
    return Column(
      children: [
        // ToggleButtons removed - Defaulting to Offering
        // const SizedBox(height: 24),
        DropdownButtonFormField<FillMaterial>(
          value: _material,
          decoration: const InputDecoration(labelText: 'Material Type', border: OutlineInputBorder()),
          items: FillMaterial.values.map((e) => DropdownMenuItem(value: e, child: Text(e.name.toUpperCase()))).toList(),
          onChanged: (v) => setState(() => _material = v!),
        ),
      ],
    );
  }

  Widget _buildDetails() {
    return Column(
      children: [
        Row(
          children: [
            Expanded(
              flex: 2,
              child: TextFormField(
                controller: _qtyController,
                decoration: const InputDecoration(labelText: 'Quantity', border: OutlineInputBorder()),
                keyboardType: TextInputType.number,
                validator: (v) => v == null || v.isEmpty ? 'Required' : null,
              ),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: DropdownButtonFormField<VolumeUnit>(
                value: _unit,
                decoration: const InputDecoration(labelText: 'Unit', border: OutlineInputBorder()),
                items: VolumeUnit.values.map((e) => DropdownMenuItem(value: e, child: Text(e.name))).toList(),
                onChanged: (v) => setState(() => _unit = v!),
              ),
            ),
          ],
        ),
        const SizedBox(height: 16),
        SwitchListTile(
          title: const Text('Is it Free?'),
          value: _isFree,
          onChanged: (v) => setState(() => _isFree = v),
        ),
        if (!_isFree)
          TextFormField(
            controller: _priceController,
            decoration: const InputDecoration(labelText: 'Price', prefixText: '\$', border: OutlineInputBorder()),
            keyboardType: TextInputType.number,
          ),
      ],
    );
  }

  Widget _buildLocation() {
    return Column(
      children: [
        if (_currentLocation != null)
          Padding(
            padding: const EdgeInsets.only(bottom: 16),
            child: StaticMapPreview(center: _currentLocation!),
          ),
        TextFormField(
          controller: _addressController,
          decoration: InputDecoration(
            labelText: 'Address / Location Description',
            border: const OutlineInputBorder(),
            prefixIcon: const Icon(Icons.location_on),
            hintText: 'e.g., 123 Main St, Springfield',
            suffixIcon: IconButton(
               icon: const Icon(Icons.map, color: Colors.blue),
               tooltip: 'Pick on Map',
               onPressed: () async {
                  final result = await Navigator.push(
                    context,
                    MaterialPageRoute(builder: (c) => LocationPickerScreen(initialLocation: _currentLocation)),
                  );
                  if (result is LocationResult) {
                     setState(() {
                        _currentLocation = result.point;
                        _addressController.text = result.address;
                     });
                  }
               },
            ),
          ),
          validator: (v) => v == null || v.isEmpty ? 'Required' : null,
          maxLines: 2,
        ),
        const SizedBox(height: 8),
        OutlinedButton.icon(
          onPressed: _getCurrentLocation,
          icon: const Icon(Icons.my_location),
          label: const Text('Use Current Location'),
        ),
      ],
    );
  }

  Widget _buildPhotos() {
    return Column(
      children: [
        TextFormField(
          controller: _descriptionController,
          decoration: const InputDecoration(labelText: 'Description (Optional)', border: OutlineInputBorder()),
          maxLines: 3,
        ),
        const SizedBox(height: 16),
        Row(
          children: [
            const Text('Photos (Optional)'),
            const Spacer(),
            IconButton(onPressed: _pickImage, icon: const Icon(Icons.add_a_photo)),
          ],
        ),
        if (_selectedPhotos.isNotEmpty)
          SizedBox(
            height: 100,
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              itemCount: _selectedPhotos.length,
              itemBuilder: (context, index) {
                return Padding(
                  padding: const EdgeInsets.only(right: 8.0),
                  child: Stack(
                    children: [
                      Image.file(File(_selectedPhotos[index].path), width: 100, height: 100, fit: BoxFit.cover),
                      Positioned(
                        right: 0,
                        top: 0,
                        child: GestureDetector(
                          onTap: () => setState(() => _selectedPhotos.removeAt(index)),
                          child: const CircleAvatar(radius: 10, backgroundColor: Colors.red, child: Icon(Icons.close, size: 12, color: Colors.white)),
                        ),
                      ),
                    ],
                  ),
                );
              },
            ),
          ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Create Listing')),
      body: Form(
        key: _formKey,
        child: Stepper( // Standard Stepper or Custom?
          type: StepperType.vertical,
          currentStep: _currentStep.index,
          onStepContinue: () {
             if (_currentStep == _Step.location && _currentLocation == null) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Please mark a location on the map or use current location')),
                );
                return;
             }

             if (_currentStep == _Step.photos) {
                _submit();
             } else {
                setState(() => _currentStep = _Step.values[_currentStep.index + 1]);
             }
          },
          onStepCancel: () {
             if (_currentStep.index > 0) {
                setState(() => _currentStep = _Step.values[_currentStep.index - 1]);
             } else {
                context.pop();
             }
          },
          controlsBuilder: (context, details) {
             return Padding(
               padding: const EdgeInsets.only(top: 16.0),
               child: Row(
                 children: [
                   ElevatedButton(
                     onPressed: _isLoading ? null : details.onStepContinue,
                     child: _currentStep == _Step.photos
                         ? (_isLoading ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator()) : const Text('Post Listing'))
                         : const Text('Next'),
                   ),
                   const SizedBox(width: 16),
                   if (_currentStep.index > 0 || !_isLoading)
                     TextButton(onPressed: _isLoading ? null : details.onStepCancel, child: Text(_currentStep.index == 0 ? 'Cancel' : 'Back')),
                 ],
               ),
             );
          },
          steps: [
            Step(
              title: const Text('Type & Material'),
              content: _buildBasicInfo(),
              isActive: _currentStep.index >= 0,
            ),
            Step(
              title: const Text('Details'),
              content: _buildDetails(),
              isActive: _currentStep.index >= 1,
            ),
            Step(
              title: const Text('Location'),
              content: _buildLocation(),
              isActive: _currentStep.index >= 2,
            ),
            Step(
              title: const Text('Photos & Description'),
              content: _buildPhotos(),
              isActive: _currentStep.index >= 3,
            ),
          ],
        ),
      ),
    );
  }
}
