# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  # Uncomment the next line if you want to use dynamic frameworks
  # use_frameworks!

  # Pods need to be installed to the Runner target
  target 'Runner' do
    pod 'Flutter', :path => '../Flutter'
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end

# Prevent Cocoapods from embedding a second Podfile
install! 'cocoapods', :disable_input_output_paths => true
